version: "2"

services:
  db:
    image: mysql:5.7
    container_name: '${PROJECT_NAME}-mysql'
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - db
    build: ./my-wordpress
    container_name: '${PROJECT_NAME}-wordpress'
    ports:
      - "${SERVER_PORT}:80"
    links:
      - db
    volumes:
      - ./wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
  wordpress-cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    container_name: '${PROJECT_NAME}-wp-cli'
    user: xfs
    volumes:
      - ./wp:/var/www/html
    command: >
      /bin/sh -c 'wp core install --path="/var/www/html" --url="http://localhost:${SERVER_PORT}" --title="test" --admin_user=admin --admin_password=admin --admin_email=admin@example.com'
volumes: 
  db_data:
  wp:
