version: "2"

services:
  db:
    image: mysql:5.7
    container_name: '${PROJECT_NAME}-mysql'
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - db
    build: ./wordpress-with-wp-cli
    container_name: '${PROJECT_NAME}-wordpress'
    ports:
      - "${LOCAL_PORT}:80"
    links:
      - db
    volumes:
      - ./wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
volumes: 
  db-data:
  wp:
